/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Metrics = IDL.Record({
  'expiredLicenses' : IDL.Nat,
  'activeLicenses' : IDL.Nat,
  'activeSOSCount' : IDL.Nat,
  'totalUsers' : IDL.Nat,
  'totalSOSCount' : IDL.Nat,
  'totalIncidents' : IDL.Nat,
});
export const SOSAlert = IDL.Record({
  'id' : IDL.Text,
  'lat' : IDL.Float64,
  'lng' : IDL.Float64,
  'status' : IDL.Text,
  'userName' : IDL.Text,
  'activatedAt' : IDL.Int,
  'userId' : IDL.Principal,
  'neighborhood' : IDL.Text,
  'lastLocationUpdate' : IDL.Int,
});
export const Incident = IDL.Record({
  'id' : IDL.Text,
  'lat' : IDL.Float64,
  'lng' : IDL.Float64,
  'confirmations' : IDL.Nat,
  'status' : IDL.Text,
  'userName' : IDL.Text,
  'userId' : IDL.Principal,
  'neighborhood' : IDL.Text,
  'createdAt' : IDL.Int,
  'description' : IDL.Text,
  'adminValidated' : IDL.Bool,
  'falseReports' : IDL.Nat,
  'incidentType' : IDL.Text,
});
export const License = IDL.Record({
  'status' : IDL.Text,
  'clientName' : IDL.Text,
  'expiryDate' : IDL.Int,
  'code' : IDL.Text,
  'activationDate' : IDL.Int,
  'assignedPhone' : IDL.Text,
});
export const UserProfile = IDL.Record({
  'id' : IDL.Principal,
  'licenseStatus' : IDL.Text,
  'neighborhood' : IDL.Text,
  'isBlocked' : IDL.Bool,
  'name' : IDL.Text,
  'licenseCode' : IDL.Text,
  'isAdmin' : IDL.Bool,
  'phone' : IDL.Text,
  'registrationDate' : IDL.Int,
  'licenseExpiry' : IDL.Int,
  'licenseStart' : IDL.Int,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const LocationShare = IDL.Record({
  'id' : IDL.Text,
  'lat' : IDL.Float64,
  'lng' : IDL.Float64,
  'ownerName' : IDL.Text,
  'ownerId' : IDL.Principal,
  'lastUpdate' : IDL.Int,
  'description' : IDL.Opt(IDL.Text),
  'isActive' : IDL.Bool,
  'shareLink' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'activateLicense' : IDL.Func([IDL.Text], [], []),
  'adminActivateLicense' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'adminBlockLicense' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'adminBlockUser' : IDL.Func([IDL.Text, IDL.Principal], [], []),
  'adminCreateLicense' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'adminGetMetrics' : IDL.Func([IDL.Text], [Metrics], ['query']),
  'adminListActiveSOSAlerts' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(SOSAlert)],
      ['query'],
    ),
  'adminListIncidents' : IDL.Func([IDL.Text], [IDL.Vec(Incident)], ['query']),
  'adminListLicenses' : IDL.Func([IDL.Text], [IDL.Vec(License)], ['query']),
  'adminListUsers' : IDL.Func([IDL.Text], [IDL.Vec(UserProfile)], ['query']),
  'adminRemoveIncident' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'adminRenewLicense' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'adminUnblockUser' : IDL.Func([IDL.Text, IDL.Principal], [], []),
  'adminValidateIncident' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'blockLicense' : IDL.Func([IDL.Text], [], []),
  'blockUser' : IDL.Func([IDL.Principal], [], []),
  'checkCallerAdminStatus' : IDL.Func([], [IDL.Bool], ['query']),
  'checkLicenseValidity' : IDL.Func([IDL.Text], [IDL.Text], ['query']),
  'confirmIncident' : IDL.Func([IDL.Text], [], []),
  'createIncident' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Float64, IDL.Float64, IDL.Text],
      [IDL.Text],
      [],
    ),
  'createLicense' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'createLocationShare' : IDL.Func(
      [IDL.Text, IDL.Float64, IDL.Float64, IDL.Text, IDL.Opt(IDL.Text)],
      [IDL.Text],
      [],
    ),
  'createSOS' : IDL.Func(
      [IDL.Text, IDL.Float64, IDL.Float64, IDL.Text],
      [IDL.Text],
      [],
    ),
  'deactivateLocationShare' : IDL.Func([IDL.Text], [], []),
  'flagFalseIncident' : IDL.Func([IDL.Text], [], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getIncidentById' : IDL.Func([IDL.Text], [Incident], ['query']),
  'getLocationShare' : IDL.Func([IDL.Text], [LocationShare], ['query']),
  'getMetrics' : IDL.Func([], [Metrics], ['query']),
  'getProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getSOSById' : IDL.Func([IDL.Text], [SOSAlert], ['query']),
  'getUser' : IDL.Func([IDL.Principal], [IDL.Opt(UserProfile)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listActiveSOSAlerts' : IDL.Func([], [IDL.Vec(SOSAlert)], ['query']),
  'listAllLicenses' : IDL.Func([], [IDL.Vec(License)], ['query']),
  'listAllUsers' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
  'listIncidents' : IDL.Func(
      [IDL.Opt(IDL.Text)],
      [IDL.Vec(Incident)],
      ['query'],
    ),
  'listOwnActiveShareSessions' : IDL.Func(
      [],
      [IDL.Vec(LocationShare)],
      ['query'],
    ),
  'registerUser' : IDL.Func([IDL.Text, IDL.Text, IDL.Text, IDL.Text], [], []),
  'removeIncident' : IDL.Func([IDL.Text], [], []),
  'renewLicense' : IDL.Func([IDL.Text], [], []),
  'resolveSOS' : IDL.Func([IDL.Text], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'setAdmin' : IDL.Func([], [], []),
  'unblockUser' : IDL.Func([IDL.Principal], [], []),
  'updateLocationShare' : IDL.Func(
      [IDL.Text, IDL.Float64, IDL.Float64],
      [],
      [],
    ),
  'updateSOSLocation' : IDL.Func([IDL.Text, IDL.Float64, IDL.Float64], [], []),
  'validateIncident' : IDL.Func([IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Metrics = IDL.Record({
    'expiredLicenses' : IDL.Nat,
    'activeLicenses' : IDL.Nat,
    'activeSOSCount' : IDL.Nat,
    'totalUsers' : IDL.Nat,
    'totalSOSCount' : IDL.Nat,
    'totalIncidents' : IDL.Nat,
  });
  const SOSAlert = IDL.Record({
    'id' : IDL.Text,
    'lat' : IDL.Float64,
    'lng' : IDL.Float64,
    'status' : IDL.Text,
    'userName' : IDL.Text,
    'activatedAt' : IDL.Int,
    'userId' : IDL.Principal,
    'neighborhood' : IDL.Text,
    'lastLocationUpdate' : IDL.Int,
  });
  const Incident = IDL.Record({
    'id' : IDL.Text,
    'lat' : IDL.Float64,
    'lng' : IDL.Float64,
    'confirmations' : IDL.Nat,
    'status' : IDL.Text,
    'userName' : IDL.Text,
    'userId' : IDL.Principal,
    'neighborhood' : IDL.Text,
    'createdAt' : IDL.Int,
    'description' : IDL.Text,
    'adminValidated' : IDL.Bool,
    'falseReports' : IDL.Nat,
    'incidentType' : IDL.Text,
  });
  const License = IDL.Record({
    'status' : IDL.Text,
    'clientName' : IDL.Text,
    'expiryDate' : IDL.Int,
    'code' : IDL.Text,
    'activationDate' : IDL.Int,
    'assignedPhone' : IDL.Text,
  });
  const UserProfile = IDL.Record({
    'id' : IDL.Principal,
    'licenseStatus' : IDL.Text,
    'neighborhood' : IDL.Text,
    'isBlocked' : IDL.Bool,
    'name' : IDL.Text,
    'licenseCode' : IDL.Text,
    'isAdmin' : IDL.Bool,
    'phone' : IDL.Text,
    'registrationDate' : IDL.Int,
    'licenseExpiry' : IDL.Int,
    'licenseStart' : IDL.Int,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const LocationShare = IDL.Record({
    'id' : IDL.Text,
    'lat' : IDL.Float64,
    'lng' : IDL.Float64,
    'ownerName' : IDL.Text,
    'ownerId' : IDL.Principal,
    'lastUpdate' : IDL.Int,
    'description' : IDL.Opt(IDL.Text),
    'isActive' : IDL.Bool,
    'shareLink' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'activateLicense' : IDL.Func([IDL.Text], [], []),
    'adminActivateLicense' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'adminBlockLicense' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'adminBlockUser' : IDL.Func([IDL.Text, IDL.Principal], [], []),
    'adminCreateLicense' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'adminGetMetrics' : IDL.Func([IDL.Text], [Metrics], ['query']),
    'adminListActiveSOSAlerts' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(SOSAlert)],
        ['query'],
      ),
    'adminListIncidents' : IDL.Func([IDL.Text], [IDL.Vec(Incident)], ['query']),
    'adminListLicenses' : IDL.Func([IDL.Text], [IDL.Vec(License)], ['query']),
    'adminListUsers' : IDL.Func([IDL.Text], [IDL.Vec(UserProfile)], ['query']),
    'adminRemoveIncident' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'adminRenewLicense' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'adminUnblockUser' : IDL.Func([IDL.Text, IDL.Principal], [], []),
    'adminValidateIncident' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'blockLicense' : IDL.Func([IDL.Text], [], []),
    'blockUser' : IDL.Func([IDL.Principal], [], []),
    'checkCallerAdminStatus' : IDL.Func([], [IDL.Bool], ['query']),
    'checkLicenseValidity' : IDL.Func([IDL.Text], [IDL.Text], ['query']),
    'confirmIncident' : IDL.Func([IDL.Text], [], []),
    'createIncident' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Float64, IDL.Float64, IDL.Text],
        [IDL.Text],
        [],
      ),
    'createLicense' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'createLocationShare' : IDL.Func(
        [IDL.Text, IDL.Float64, IDL.Float64, IDL.Text, IDL.Opt(IDL.Text)],
        [IDL.Text],
        [],
      ),
    'createSOS' : IDL.Func(
        [IDL.Text, IDL.Float64, IDL.Float64, IDL.Text],
        [IDL.Text],
        [],
      ),
    'deactivateLocationShare' : IDL.Func([IDL.Text], [], []),
    'flagFalseIncident' : IDL.Func([IDL.Text], [], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getIncidentById' : IDL.Func([IDL.Text], [Incident], ['query']),
    'getLocationShare' : IDL.Func([IDL.Text], [LocationShare], ['query']),
    'getMetrics' : IDL.Func([], [Metrics], ['query']),
    'getProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getSOSById' : IDL.Func([IDL.Text], [SOSAlert], ['query']),
    'getUser' : IDL.Func([IDL.Principal], [IDL.Opt(UserProfile)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listActiveSOSAlerts' : IDL.Func([], [IDL.Vec(SOSAlert)], ['query']),
    'listAllLicenses' : IDL.Func([], [IDL.Vec(License)], ['query']),
    'listAllUsers' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
    'listIncidents' : IDL.Func(
        [IDL.Opt(IDL.Text)],
        [IDL.Vec(Incident)],
        ['query'],
      ),
    'listOwnActiveShareSessions' : IDL.Func(
        [],
        [IDL.Vec(LocationShare)],
        ['query'],
      ),
    'registerUser' : IDL.Func([IDL.Text, IDL.Text, IDL.Text, IDL.Text], [], []),
    'removeIncident' : IDL.Func([IDL.Text], [], []),
    'renewLicense' : IDL.Func([IDL.Text], [], []),
    'resolveSOS' : IDL.Func([IDL.Text], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'setAdmin' : IDL.Func([], [], []),
    'unblockUser' : IDL.Func([IDL.Principal], [], []),
    'updateLocationShare' : IDL.Func(
        [IDL.Text, IDL.Float64, IDL.Float64],
        [],
        [],
      ),
    'updateSOSLocation' : IDL.Func(
        [IDL.Text, IDL.Float64, IDL.Float64],
        [],
        [],
      ),
    'validateIncident' : IDL.Func([IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };