/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Incident {
  'id' : string,
  'lat' : number,
  'lng' : number,
  'confirmations' : bigint,
  'status' : string,
  'userName' : string,
  'userId' : Principal,
  'neighborhood' : string,
  'createdAt' : bigint,
  'description' : string,
  'adminValidated' : boolean,
  'falseReports' : bigint,
  'incidentType' : string,
}
export interface License {
  'status' : string,
  'clientName' : string,
  'expiryDate' : bigint,
  'code' : string,
  'activationDate' : bigint,
  'assignedPhone' : string,
}
export interface LocationShare {
  'id' : string,
  'lat' : number,
  'lng' : number,
  'ownerName' : string,
  'ownerId' : Principal,
  'lastUpdate' : bigint,
  'description' : [] | [string],
  'isActive' : boolean,
  'shareLink' : string,
}
export interface Metrics {
  'expiredLicenses' : bigint,
  'activeLicenses' : bigint,
  'activeSOSCount' : bigint,
  'totalUsers' : bigint,
  'totalSOSCount' : bigint,
  'totalIncidents' : bigint,
}
export interface SOSAlert {
  'id' : string,
  'lat' : number,
  'lng' : number,
  'status' : string,
  'userName' : string,
  'activatedAt' : bigint,
  'userId' : Principal,
  'neighborhood' : string,
  'lastLocationUpdate' : bigint,
}
export interface UserProfile {
  'id' : Principal,
  'licenseStatus' : string,
  'neighborhood' : string,
  'isBlocked' : boolean,
  'name' : string,
  'licenseCode' : string,
  'isAdmin' : boolean,
  'phone' : string,
  'registrationDate' : bigint,
  'licenseExpiry' : bigint,
  'licenseStart' : bigint,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'activateLicense' : ActorMethod<[string], undefined>,
  'adminActivateLicense' : ActorMethod<[string, string], undefined>,
  'adminBlockLicense' : ActorMethod<[string, string], undefined>,
  'adminBlockUser' : ActorMethod<[string, Principal], undefined>,
  'adminCreateLicense' : ActorMethod<
    [string, string, string, string],
    undefined
  >,
  'adminGetMetrics' : ActorMethod<[string], Metrics>,
  'adminListActiveSOSAlerts' : ActorMethod<[string], Array<SOSAlert>>,
  'adminListIncidents' : ActorMethod<[string], Array<Incident>>,
  'adminListLicenses' : ActorMethod<[string], Array<License>>,
  'adminListUsers' : ActorMethod<[string], Array<UserProfile>>,
  'adminRemoveIncident' : ActorMethod<[string, string], undefined>,
  'adminRenewLicense' : ActorMethod<[string, string], undefined>,
  'adminUnblockUser' : ActorMethod<[string, Principal], undefined>,
  'adminValidateIncident' : ActorMethod<[string, string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'blockLicense' : ActorMethod<[string], undefined>,
  'blockUser' : ActorMethod<[Principal], undefined>,
  'checkCallerAdminStatus' : ActorMethod<[], boolean>,
  'checkLicenseValidity' : ActorMethod<[string], string>,
  'confirmIncident' : ActorMethod<[string], undefined>,
  'createIncident' : ActorMethod<
    [string, string, string, number, number, string],
    string
  >,
  'createLicense' : ActorMethod<[string, string, string], undefined>,
  'createLocationShare' : ActorMethod<
    [string, number, number, string, [] | [string]],
    string
  >,
  'createSOS' : ActorMethod<[string, number, number, string], string>,
  'deactivateLocationShare' : ActorMethod<[string], undefined>,
  'flagFalseIncident' : ActorMethod<[string], undefined>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getIncidentById' : ActorMethod<[string], Incident>,
  'getLocationShare' : ActorMethod<[string], LocationShare>,
  'getMetrics' : ActorMethod<[], Metrics>,
  'getProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getSOSById' : ActorMethod<[string], SOSAlert>,
  'getUser' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'listActiveSOSAlerts' : ActorMethod<[], Array<SOSAlert>>,
  'listAllLicenses' : ActorMethod<[], Array<License>>,
  'listAllUsers' : ActorMethod<[], Array<UserProfile>>,
  'listIncidents' : ActorMethod<[[] | [string]], Array<Incident>>,
  'listOwnActiveShareSessions' : ActorMethod<[], Array<LocationShare>>,
  'registerUser' : ActorMethod<[string, string, string, string], undefined>,
  'removeIncident' : ActorMethod<[string], undefined>,
  'renewLicense' : ActorMethod<[string], undefined>,
  'resolveSOS' : ActorMethod<[string], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'setAdmin' : ActorMethod<[], undefined>,
  'unblockUser' : ActorMethod<[Principal], undefined>,
  'updateLocationShare' : ActorMethod<[string, number, number], undefined>,
  'updateSOSLocation' : ActorMethod<[string, number, number], undefined>,
  'validateIncident' : ActorMethod<[string], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];