/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface License {
    status: string;
    clientName: string;
    expiryDate: bigint;
    code: string;
    activationDate: bigint;
    assignedPhone: string;
}
export interface SOSAlert {
    id: string;
    lat: number;
    lng: number;
    status: string;
    userName: string;
    activatedAt: bigint;
    userId: Principal;
    neighborhood: string;
    lastLocationUpdate: bigint;
}
export interface Incident {
    id: string;
    lat: number;
    lng: number;
    confirmations: bigint;
    status: string;
    userName: string;
    userId: Principal;
    neighborhood: string;
    createdAt: bigint;
    description: string;
    adminValidated: boolean;
    falseReports: bigint;
    incidentType: string;
}
export interface LocationShare {
    id: string;
    lat: number;
    lng: number;
    ownerName: string;
    ownerId: Principal;
    lastUpdate: bigint;
    description?: string;
    isActive: boolean;
    shareLink: string;
}
export interface UserProfile {
    id: Principal;
    licenseStatus: string;
    name: string;
    licenseCode: string;
    isAdmin: boolean;
    registrationDate: bigint;
    licenseExpiry: bigint;
    licenseStart: bigint;
}
export interface Metrics {
    expiredLicenses: bigint;
    activeLicenses: bigint;
    activeSOSCount: bigint;
    totalUsers: bigint;
    totalSOSCount: bigint;
    totalIncidents: bigint;
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    activateLicense(code: string): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    blockLicense(code: string): Promise<void>;
    blockUser(userId: Principal): Promise<void>;
    checkLicenseValidity(code: string): Promise<string>;
    confirmIncident(id: string): Promise<void>;
    createIncident(userName: string, incidentType: string, description: string, lat: number, lng: number, neighborhood: string): Promise<string>;
    createLicense(code: string, clientName: string, phone: string): Promise<void>;
    createLocationShare(ownerName: string, lat: number, lng: number, shareLink: string, description: string | null): Promise<string>;
    createSOS(userName: string, lat: number, lng: number, neighborhood: string): Promise<string>;
    deactivateLocationShare(id: string): Promise<void>;
    flagFalseIncident(id: string): Promise<void>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getIncidentById(id: string): Promise<Incident>;
    getLocationShare(id: string): Promise<LocationShare>;
    getMetrics(): Promise<Metrics>;
    getProfile(): Promise<UserProfile | null>;
    getSOSById(id: string): Promise<SOSAlert>;
    getUser(userId: Principal): Promise<UserProfile | null>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    listActiveSOSAlerts(): Promise<Array<SOSAlert>>;
    listAllLicenses(): Promise<Array<License>>;
    listAllUsers(): Promise<Array<UserProfile>>;
    listIncidents(incidentType: string | null): Promise<Array<Incident>>;
    listOwnActiveShareSessions(): Promise<Array<LocationShare>>;
    registerUser(name: string, phone: string, neighborhood: string, licenseCode: string): Promise<void>;
    removeIncident(id: string): Promise<void>;
    renewLicense(code: string): Promise<void>;
    resolveSOS(id: string): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    setAdmin(): Promise<void>;
    unblockUser(userId: Principal): Promise<void>;
    updateLocationShare(id: string, lat: number, lng: number): Promise<void>;
    updateSOSLocation(id: string, lat: number, lng: number): Promise<void>;
    validateIncident(id: string): Promise<void>;
}
import type { LocationShare as _LocationShare, UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async activateLicense(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.activateLicense(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.activateLicense(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async blockLicense(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.blockLicense(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.blockLicense(arg0);
            return result;
        }
    }
    async blockUser(arg0: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.blockUser(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.blockUser(arg0);
            return result;
        }
    }
    async checkLicenseValidity(arg0: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.checkLicenseValidity(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.checkLicenseValidity(arg0);
            return result;
        }
    }
    async confirmIncident(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.confirmIncident(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.confirmIncident(arg0);
            return result;
        }
    }
    async createIncident(arg0: string, arg1: string, arg2: string, arg3: number, arg4: number, arg5: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.createIncident(arg0, arg1, arg2, arg3, arg4, arg5);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createIncident(arg0, arg1, arg2, arg3, arg4, arg5);
            return result;
        }
    }
    async createLicense(arg0: string, arg1: string, arg2: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createLicense(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createLicense(arg0, arg1, arg2);
            return result;
        }
    }
    async createLocationShare(arg0: string, arg1: number, arg2: number, arg3: string, arg4: string | null): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.createLocationShare(arg0, arg1, arg2, arg3, to_candid_opt_n3(this._uploadFile, this._downloadFile, arg4));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createLocationShare(arg0, arg1, arg2, arg3, to_candid_opt_n3(this._uploadFile, this._downloadFile, arg4));
            return result;
        }
    }
    async createSOS(arg0: string, arg1: number, arg2: number, arg3: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.createSOS(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createSOS(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async deactivateLocationShare(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deactivateLocationShare(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deactivateLocationShare(arg0);
            return result;
        }
    }
    async flagFalseIncident(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.flagFalseIncident(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.flagFalseIncident(arg0);
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async getIncidentById(arg0: string): Promise<Incident> {
        if (this.processError) {
            try {
                const result = await this.actor.getIncidentById(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getIncidentById(arg0);
            return result;
        }
    }
    async getLocationShare(arg0: string): Promise<LocationShare> {
        if (this.processError) {
            try {
                const result = await this.actor.getLocationShare(arg0);
                return from_candid_LocationShare_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLocationShare(arg0);
            return from_candid_LocationShare_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMetrics(): Promise<Metrics> {
        if (this.processError) {
            try {
                const result = await this.actor.getMetrics();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMetrics();
            return result;
        }
    }
    async getProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getProfile();
                return from_candid_opt_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProfile();
            return from_candid_opt_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSOSById(arg0: string): Promise<SOSAlert> {
        if (this.processError) {
            try {
                const result = await this.actor.getSOSById(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSOSById(arg0);
            return result;
        }
    }
    async getUser(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUser(arg0);
                return from_candid_opt_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUser(arg0);
            return from_candid_opt_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async listActiveSOSAlerts(): Promise<Array<SOSAlert>> {
        if (this.processError) {
            try {
                const result = await this.actor.listActiveSOSAlerts();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listActiveSOSAlerts();
            return result;
        }
    }
    async listAllLicenses(): Promise<Array<License>> {
        if (this.processError) {
            try {
                const result = await this.actor.listAllLicenses();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listAllLicenses();
            return result;
        }
    }
    async listAllUsers(): Promise<Array<UserProfile>> {
        if (this.processError) {
            try {
                const result = await this.actor.listAllUsers();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listAllUsers();
            return result;
        }
    }
    async listIncidents(arg0: string | null): Promise<Array<Incident>> {
        if (this.processError) {
            try {
                const result = await this.actor.listIncidents(to_candid_opt_n3(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listIncidents(to_candid_opt_n3(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async listOwnActiveShareSessions(): Promise<Array<LocationShare>> {
        if (this.processError) {
            try {
                const result = await this.actor.listOwnActiveShareSessions();
                return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listOwnActiveShareSessions();
            return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async registerUser(arg0: string, arg1: string, arg2: string, arg3: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.registerUser(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.registerUser(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async removeIncident(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.removeIncident(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeIncident(arg0);
            return result;
        }
    }
    async renewLicense(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.renewLicense(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.renewLicense(arg0);
            return result;
        }
    }
    async resolveSOS(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.resolveSOS(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.resolveSOS(arg0);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async setAdmin(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setAdmin();
            return result;
        }
    }
    async unblockUser(arg0: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.unblockUser(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.unblockUser(arg0);
            return result;
        }
    }
    async updateLocationShare(arg0: string, arg1: number, arg2: number): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateLocationShare(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateLocationShare(arg0, arg1, arg2);
            return result;
        }
    }
    async updateSOSLocation(arg0: string, arg1: number, arg2: number): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateSOSLocation(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateSOSLocation(arg0, arg1, arg2);
            return result;
        }
    }
    async validateIncident(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.validateIncident(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.validateIncident(arg0);
            return result;
        }
    }
}
function from_candid_LocationShare_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _LocationShare): LocationShare {
    return from_candid_record_n8(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n6(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    lat: number;
    lng: number;
    ownerName: string;
    ownerId: Principal;
    lastUpdate: bigint;
    description: [] | [string];
    isActive: boolean;
    shareLink: string;
}): {
    id: string;
    lat: number;
    lng: number;
    ownerName: string;
    ownerId: Principal;
    lastUpdate: bigint;
    description?: string;
    isActive: boolean;
    shareLink: string;
} {
    return {
        id: value.id,
        lat: value.lat,
        lng: value.lng,
        ownerName: value.ownerName,
        ownerId: value.ownerId,
        lastUpdate: value.lastUpdate,
        description: record_opt_to_undefined(from_candid_opt_n9(_uploadFile, _downloadFile, value.description)),
        isActive: value.isActive,
        shareLink: value.shareLink
    };
}
function from_candid_variant_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_vec_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_LocationShare>): Array<LocationShare> {
    return value.map((x)=>from_candid_LocationShare_n7(_uploadFile, _downloadFile, x));
}
function to_candid_UserRole_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
